baseurl: ""
highlighter: rouge
name: My developer's notes | Ulysse Buonomo
description: >-
  Some of the stuff I don't want to forget a few years from now.
url: https://ulysse.md
exclude:
  - bin
  - Makefile
  - README.md
  - TODO.md
