#ifndef GAME_OF_LIFE_H
#define GAME_OF_LIFE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

/* # Data */

typedef struct game_of_life game_of_life;

typedef void (*set_pixel_fn)(game_of_life self, size_t h, size_t w, bool is_alive);

struct game_of_life {
	size_t height;
	size_t board_height;
	size_t board_width;
	size_t width;
	size_t pixel;
	bool **board;
	bool is_tor;
	void *data; /* User defined data, can be used in `set_pixel` */
	void (*set_pixel)(game_of_life self, size_t h, size_t w, bool is_alive);
};




/* # Functions */


game_of_life *gol_init(size_t height, size_t width, size_t pixel, bool is_tor, set_pixel_fn);
/* Does not clear data pointer. If defined, clear it before calling this method. */
void gol_clear(game_of_life*);
void gol_step(game_of_life);
/* Use `set_pixel_fn` to imprint every pixels, note that a pixel may be written
 * twice. */
void gol_render(game_of_life);
void gol_fill_random(game_of_life);
void gol_empty(game_of_life);
/* 1 error, 0 ok.
 * The function may error even after partially editing. */
int gol_insert_rle(game_of_life, size_t h, size_t w, size_t height, size_t width, const char *rle);

size_t gol_neighbors(game_of_life, size_t h, size_t w);
/* Returns wether a given cell is alive.
 * When out of bound:
 * - if game is a tor, get element using a modulo,
 * - otherwise, consider it is dead (e.g. false) */
bool gol_get(game_of_life, size_t h, size_t w);

/* # Some predefined game of life structures */

/* OO
 * OO */
#define BLOCK(game, h, w) gol_insert_rle(game, h, w, 2, 2, "2o$2o!")

/* .......O...................................................................................O.......
 * ......OOO.................................................................................OOO......
 * ....OO.OOO....................OOO.........OOO.........OOO.........OOO....................OOO.OO....
 * .....O..O.OO....O....O.......O...O.......O...O.......O...O.......O...O.......O....O....OO.O..O.....
 * ..OO.O....O.O.OO.OO.OOO.....OO...OO.....OO...OO.....OO...OO.....OO...OO.....OOO.OO.OO.O.O....O.OO..
 * ..OO.O.O..O.O.......OOOO...OO.O.O.OO...OO.O.O.OO...OO.O.O.OO...OO.O.O.OO...OOOO.......O.O..O.O.OO..
 * ..O........OOO.O.O.OO..OO.OO.OO.OO.OO.OO.OO.OO.OO.OO.OO.OO.OO.OO.OO.OO.OO.OO..OO.O.O.OOO........O..
 * .OO.......OO............O.O...O.O...O.O...O.O...O.O...O.O...O.O...O.O...O.O............OO.......OO.
 * ...................................................................................................
 * .....OOO...............OO.OO.OO.OO.OO.OO.OO.OO.OO.OO.OO.OO.OO.OO.OO.OO.OO.OO...............OOO.....
 * ....O...O.................................................................................O...O....
 * ...OO....O...........OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO...........O....OO...
 * ..O.O.OO.OO...OOO..OO.O....O.....O........O......O......O........O.....O....O.OO..OOO...OO.OO.O.O..
 * .OO.O....O.OO.OOO.O.............................................................O.OOO.OO.O....O.OO.
 * O....O...O....O.O....O....O.O.O.O.O......O.O.OO.O.O.OO.O.O......O.O.O.O.O....O....O.O....O...O....O
 * ............O.....OO................O..O...................O..O................OO.....O............
 * OO.......OO.........................O..O...................O..O.........................OO.......OO
 * ...................................................................................................
 * ....................................O..O...................O..O....................................
 * .....................................OO.....................OO.....................................
 * ...................................................................................................
 * ...................................................................................................
 * ...................................................................................................
 * ...................................................................................................
 * .................................................O.................................................
 * ................................................OOO................................................
 * ...............................................O...O...............................................
 * .....................................OO........OO.OO........OO.....................................
 * .....................................OO.....................OO.....................................
 * https://www.conwaylife.com/wiki/Pi_ship_1 */
#define PI_SHIP(game, h, w) gol_insert_rle(game, h, w, 29, 99, "7bo83bo$6b3o81b3o$4b2ob3o20b3o9b3o9b3o9b3o20b3ob2o$5bo2bo"\
"b2o4bo4bo7bo3bo7bo3bo7bo3bo7bo3bo7bo4bo4b2obo2bo$2b2obo4bobob2ob2ob3o5b2o3b2o5b2o3b2o5b2o3b2o5b2o3b2o5b3ob2ob2obobo4"\
"bob2o$2b2obobo2bobo7b4o3b2obobob2o3b2obobob2o3b2obobob2o3b2obobob2o3b4o7bobo2bobob2o$2bo8b3obobob2o2b2ob2ob2ob2ob2ob"\
"2ob2ob2ob2ob2ob2ob2ob2ob2ob2ob2ob2ob2o2b2obobob3o8bo$b2o7b2o12bobo3bobo3bobo3bobo3bobo3bobo3bobo3bobo3bobo12b2o7b2o2"\
"$5b3o15b2ob2ob2ob2ob2ob2ob2ob2ob2ob2ob2ob2ob2ob2ob2ob2ob2ob2o15b3o$4bo3bo81bo3bo$3b2o4bo11b57o11bo4b2o$2bobob2ob2o3b"\
"3o2b2obo4bo5bo8bo6bo6bo8bo5bo4bob2o2b3o3b2ob2obobo$b2obo4bob2ob3obo61bob3ob2obo4bob2o$o4bo3bo4bobo4bo4bobobobobo6bob"\
"ob2obobob2obobo6bobobobobo4bo4bobo4bo3bo4bo$12bo5b2o16bo2bo19bo2bo16b2o5bo$2o7b2o25bo2bo19bo2bo25b2o7b2o2$36bo2bo19b"\
"o2bo$37b2o21b2o5$49bo$48b3o$47bo3bo$37b2o8b2ob2o8b2o$37b2o21b2o!")

/* ..........OO.OO...............OO.OO....................................
 * ..........OO.O....OO.....OO....O.OO....................................
 * .............O..O...OO.OO...O..O.......................................
 * .............OO.O...........O.OO......O................................
 * ................O...........O........OOO...............................
 * ........O.O......O...O.O...O.......OO...O..............................
 * ......OOO.OOO.....OOO...OOO........OOO..OO.............................
 * .....O.......O.....O.....O..............O.O............................
 * ......O.OOOOOO...OOO.....OOO....OO..OOOO.OOO...........................
 * ......OO....O....OOO.....OOO....OO.O....O...O..........................
 * ........O...OO....OO.....OO....O.O.O.OO.O...OO.........................
 * .......O.O..O.O.....O...O.....OO...O.OO.O.O.O..........................
 * ........O..O......O..O.O..O....O...O....O.OO...........................
 * ...........O...O.O...O.O...O....OOO.OOOO..OO...........................
 * ...........O...O..O..O.O..O......O.O................O...O..............
 * ...........O......OOO...OOO.......OO..OOO..........O.O.O.O.............
 * ...........O..O....................O...OO...........OO.OO..............
 * ............O.......O...............OOO................................
 * ..........O.O.O.....O................O.................................
 * .........O.O.OO.................................OO.........OO..........
 * .........O.O......O...O.......O.................O.OOOO.OOOO.O..........
 * ..........OO....OOO.O.OOO......O.................O...O.O...O...........
 * ...............O...OO....O...OOO.................O...O.O...O...........
 * ...............O.OO..OO.O.O.......................OOO...OOO............
 * ................O..OO..OO.O............................................
 * .................OO..OO.O.OO...........................................
 * ...........OOO.....O..O.O.O..O......O..................................
 * ..........OOOOOO...OOOO.OO..OO.......O....O..O....................O..O.
 * ..........O.OOO.O......O...........OOO........O.......................O
 * .........O...O.OO....O.O.......OO.........O...O...................O...O
 * .........OOOO.OOOO...OO.........OO.........OOOO....................OOOO
 * .......OO....O.OOO.............O.......................................
 * .....OO.O.OO.O..OO.....................................................
 * ....OO..O.OO.O.OO.................OO...................................
 * ....OOO.O....OO..................OO....................................
 * ....OOOO.OOOO............OO........O...................................
 * OO...OO.O...O.............OO.........................OO................
 * OO...O.OOO.O.............O..........................O.O................
 * ......OOOOOO........................................O..................
 * OOOO....OOO.............................OO....OO..OO.OOOO..............
 * O..O...................................OO.....O..O.O....O..............
 * ...................OO.....OO.............O......OO.O.OO..OO............
 * ....................OO.....O.....................O.O...OO..O...........
 * ..........O........O.....O.......................O.O.OO..OO.O..........
 * ..........OO...........OOOO.......................O....O....O..........
 * ..OOO......OO.........O....O..OO..............OO...OOO.O.OOO....OO.....
 * ...O.O....OO.........O.OO.OO..O.........OO...OO......OO.OO......O.O....
 * ....OO...............O..O...OO..O......O..O....O.............OO.O.O....
 * ....................OO.O..OO..OOOOO...O.O.O..................O.O.O.....
 * ....OO............O....O.O.O.O.....O.O..O.OO...................O.......
 * ...O.O....OO......O.OO..O..O.O.OO.OO.OO.O...O.................OO.......
 * ..OOO......OO.....O...O.O.OO.O.OO.O.....OO.OOO...............OOO.......
 * ..........OO........OO.O.O...O.....O.O.O...OOO...............OOO.......
 * ..........O..........O.O.O...O.OOO.O..OO...OOO....O.....O....OOO.......
 * .....................O..O.....OO..OO.......OOO...OOO...OOO...OOO...O...
 * ......................OO.........O.O..O.OO..O...O..OO.OO..O...OO..O.O..
 * O..O..............OO........OOO.OO.OOOO.O.OO....OOO.....OOO.......O..O.
 * OOOO...OO..........O........O..O...O...OO.O....................O.......
 * ......O...OOOOOOOOO..........O.O.OO.OO...O..O..................OOOOOO.O
 * OO....O.O.OOOOOOO..OOO......OO.OO.O.O.OO.O.OO.................O.......O
 * OO...OO.OO..OOOO..O..O..................O.O....................OOO.OOO.
 * ........O..O.......OO...................O.O........OO.OO.........O.O...
 * .....OO.O.O.O............................O.......OO.O.O.OO.............
 * ......O....O................................OO...O.......O...OO........
 * ......O.OOO.................................O....OOO...OOO....O........
 * .......OO................................OO.O.................O.OO.....
 * .........................................OO.OO...............OO.OO.....
 * https://www.conwaylife.com/wiki/Period-24_glider_gun */
#define P48_LWSS_GUN(game, h, w) gol_insert_rle(game, h, w, 67, 71, "10b2ob2o15b2ob2o$10b2obo4b2o5b2o4bob2o$13bo2bo3b2ob2"\
"o3bo2bo$13b2obo11bob2o6bo$16bo11bo8b3o$8bobo6bo3bobo3bo7b2o3bo$6b3ob3o5b3o3b3o8b3o2b2o$5bo7bo5bo5bo14bobo$6bob6o3b3o"\
"5b3o4b2o2b4ob3o$6b2o4bo4b3o5b3o4b2obo4bo3bo$8bo3b2o4b2o5b2o4bobobob2obo3b2o$7bobo2bobo5bo3bo5b2o3bob2obobobo$8bo2bo6"\
"bo2bobo2bo4bo3bo4bob2o$11bo3bobo3bobo3bo4b3ob4o2b2o$11bo3bo2bo2bobo2bo6bobo16bo3bo$11bo6b3o3b3o7b2o2b3o10bobobobo$11"\
"bo2bo20bo3b2o11b2ob2o$12bo7bo15b3o$10bobobo5bo16bo$9bobob2o33b2o9b2o$9bobo6bo3bo7bo17bob4ob4obo$10b2o4b3obob3o6bo17b"\
"o3bobo3bo$15bo3b2o4bo3b3o17bo3bobo3bo$15bob2o2b2obobo23b3o3b3o$16bo2b2o2b2obo$17b2o2b2obob2o$11b3o5bo2bobobo2bo6bo$1"\
"0b6o3b4ob2o2b2o7bo4bo2bo20bo2bo$10bob3obo6bo11b3o8bo23bo$9bo3bob2o4bobo7b2o9bo3bo19bo3bo$9b4ob4o3b2o9b2o9b4o20b4o$7b"\
"2o4bob3o13bo$5b2obob2obo2b2o$4b2o2bob2obob2o17b2o$4b3obo4b2o18b2o$4b4ob4o12b2o8bo$2o3b2obo3bo13b2o25b2o$2o3bob3obo13"\
"bo26bobo$6b6o40bo$4o4b3o29b2o4b2o2b2ob4o$o2bo35b2o5bo2bobo4bo$19b2o5b2o13bo6b2obob2o2b2o$20b2o5bo21bobo3b2o2bo$10bo8"\
"bo5bo23bobob2o2b2obo$10b2o11b4o23bo4bo4bo$2b3o6b2o9bo4bo2b2o14b2o3b3obob3o4b2o$3bobo4b2o9bob2ob2o2bo9b2o3b2o6b2ob2o6"\
"bobo$4b2o15bo2bo3b2o2bo6bo2bo4bo13b2obobo$20b2obo2b2o2b5o3bobobo18bobobo$4b2o12bo4bobobobo5bobo2bob2o19bo$3bobo4b2o6"\
"bob2o2bo2bobob2ob2ob2obo3bo17b2o$2b3o6b2o5bo3bobob2obob2obo5b2ob3o15b3o$10b2o8b2obobo3bo5bobobo3b3o15b3o$10bo10bobob"\
"o3bob3obo2b2o3b3o4bo5bo4b3o$21bo2bo5b2o2b2o7b3o3b3o3b3o3b3o3bo$22b2o9bobo2bob2o2bo3bo2b2ob2o2bo3b2o2bobo$o2bo14b2o8b"\
"3ob2ob4obob2o4b3o5b3o7bo2bo$4o3b2o10bo8bo2bo3bo3b2obo20bo$6bo3b9o10bobob2ob2o3bo2bo18b6obo$2o4bobob7o2b3o6b2ob2obobo"\
"b2obob2o17bo7bo$2o3b2ob2o2b4o2bo2bo18bobo20b3ob3o$8bo2bo7b2o19bobo8b2ob2o9bobo$5b2obobobo28bo7b2obobob2o$6bo4bo32b2o"\
"3bo7bo3b2o$6bob3o33bo4b3o3b3o4bo$7b2o32b2obo17bob2o$41b2ob2o15b2ob2o!")

/* ...........OO.................................
 * ...........O..OO..............................
 * ............O.O.O.............................
 * ...........OO.O..O...........O................
 * ..........O.....OO.........OOO................
 * ...........OO...O.........O...................
 * ........OOO.....O.........OO..................
 * ........O..OOO..O.............................
 * ...........O.........O........................
 * ............O.O......O................OO......
 * .........OOO.....O..O.............OO...O......
 * .........O.....OO.....O............O...O.O....
 * .....................OO............O.OO.O.O.OO
 * ....................................O.O.O.OO.O
 * ..............................................
 * ...OO..................................O.OOOO.
 * ....O.............................OO...O.O..O.
 * ....O.O...........................OO..O....O..
 * .....OO................................O.OO...
 * ..............................................
 * ..............................................
 * ...................................OO.........
 * ..........OOO....................O.OO.........
 * .........OO.O....................OOO..........
 * .........OO...................................
 * ..............................................
 * ..............................................
 * ...OO.O................................OO.....
 * ..O....O..OO...........................O.O....
 * .O..O.O...OO.............................O....
 * .OOOO.O..................................OO...
 * ..............................................
 * O.OO.O.O.O....................................
 * OO.O.O.OO.O............OO.....................
 * ....O.O...O............O.....OO.....O.........
 * ......O...OO.............O..O.....OOO.........
 * ......OO................O......O.O............
 * ........................O.........O...........
 * .............................O..OOO..O........
 * ..................OO.........O.....OOO........
 * ...................O.........O...OO...........
 * ................OOO.........OO.....O..........
 * ................O...........O..O.OO...........
 * .............................O.O.O............
 * ..............................OO..O...........
 * .................................OO...........
 * https://www.conwaylife.com/wiki/P49_bumper_loop */
#define P49_BUMPER_LOOP(game, h, w) gol_insert_rle(game, h, w, 46, 46, "11b2o$11bo2b2o$12bobobo$11b2obo2bo11bo$10bo5b"\
"2o9b3o$11b2o3bo9bo$8b3o5bo9b2o$8bo2b3o2bo$11bo9bo$12bobo6bo16b2o$9b3o5bo2bo13b2o3bo$9bo5b2o5bo12bo3bobo$21b2o12bob2o"\
"bobob2o$36bobobob2obo2$3b2o34bob4o$4bo29b2o3bobo2bo$4bobo27b2o2bo4bo$5b2o32bob2o3$35b2o$10b3o20bob2o$9b2obo20b3o$9b2"\
"o3$3b2obo32b2o$2bo4bo2b2o27bobo$bo2bobo3b2o29bo$b4obo34b2o2$ob2obobobo$2obobob2obo12b2o$4bobo3bo12bo5b2o5bo$6bo3b2o1"\
"3bo2bo5b3o$6b2o16bo6bobo$24bo9bo$29bo2b3o2bo$18b2o9bo5b3o$19bo9bo3b2o$16b3o9b2o5bo$16bo11bo2bob2o$29bobobo$30b2o2bo$"\
"33b2o!")

/* ..O....O..
 * OO.OOOO.OO
 * ..O....O..
 * https://conwaylife.com/wiki/Pentadecathlon */
#define PENTADECATHLON(game, h, w) gol_insert_rle(game, h, w, 3, 10, "2bo4bo2b$2ob4ob2o$2bo4bo!")

#ifdef __cplusplus
}
#endif

#endif // GAME_OF_LIFE_H
